package com.pradeep_test.pub_bzs_cns_all_bre_data_rule_edit;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class cns_transaction_file implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CNS_TRANSACTION_FILE_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "CNS_TRANSACTION_FILE_ID_SEQ", name = "CNS_TRANSACTION_FILE_ID_GENERATOR")
    private java.lang.Long id;

    public cns_transaction_file() {
    }
    
    public cns_transaction_file(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}